name: CI-CD ğŸš€

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted ğŸ’»
    steps:
      - name: ğŸ” Autenticar no Docker Hub
        run: echo "Executando o comando Docker login"

      - name: ğŸ› ï¸ ConstruÃ§Ã£o da Imagem Docker
        run: echo "Executando o comando Docker build"

      - name: ğŸš¢ Envio da Imagem Docker
        run: echo "Executando o comando Docker push"

  cd:
    runs-on: self-hosted ğŸ’»
    needs: [ci]
    steps:
      - name: ğŸ” Autenticar na AWS
        run: echo "Executando o comando aws configure"

      - name: ğŸ› ï¸ Configurar o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"

      - name: ğŸš€ Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando kubectl apply"
